JNG 4577 tranfrer object auto mapping
BlackBeltTechnology/judo-tatami-jsl pull request #149
Opened 2023-03-09 14:08 UTC by robertcsakany

2023-03-09 16:51 UTC, noherczeg requested changes

2023-03-09 16:51 UTC, noherczeg commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/structure/entityDeclarationAutoMappedTransferRelation.etl
> +      guard: generateDefaultTransferObject and s.referenceType.isKindOf(JSL!EntityDeclaration)
Wrong guard

2023-03-09 16:51 UTC, noherczeg commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/structure/entityDeclarationAutoMappedTransferRelation.etl
> +        log.debug("Created TransferObjectRelation for AutoMappedTransferObjectType: [" + t.name + "] into [" + t.eContainer.name + "]");
derived

2023-03-09 16:51 UTC, noherczeg commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/structure/entityDeclarationAutoMappedTransferRelation.etl
> +        log.debug("Clone TransferObjectRelation for AutoMappedTransferObjectType: [" + t.name + "]");
derived

2023-03-09 16:51 UTC, noherczeg commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/structure/transferDeclarationTransferAttribute.etl
> +        //if (s.defaultExpression.isDefined()) {
why comment this?

2023-03-10 09:04 UTC, noherczeg approved these changes

2023-03-10 12:14 UTC, bencegelei requested changes

2023-03-10 12:14 UTC, bencegelei commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/structure/entityDeclarationAutoMappedTransferAttribute.etl
> +        t.setId("(jsl/" + s.getId() + ")/CreateTransferAttributeForAutoTransferObjectType");
> `t.setId("(jsl/" + s.getId() + ")/CreateTransferAttributeForAutoTransferObjectType");`

CreateTransferAttributeForAutoMappedTransferObjectType?

2023-03-10 12:14 UTC, bencegelei commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/structure/entityDeclarationAutoMappedTransferAttribute.etl
> +}
Both **default** and **derived** terms used in this case. Is it intentional or a typo?

2023-03-10 12:14 UTC, bencegelei commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/structure/entityDeclarationAutoMappedTransferObjectType.etl
> +					// Primitive derives
> Derives

Derived

2023-03-10 12:14 UTC, bencegelei commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/structure/entityDeclarationAutoMappedTransferRelation.etl
> +        t.setId("(jsl/" + s.getId() + ")/CloneTransferObjectEmbeddedRelationForDefaultTransferObjectType");
> `t.setId("(jsl/" + s.getId() + ")/CloneTransferObjectEmbeddedRelationForDefaultTransferObjectType");`

CloneTransferObjectEmbeddedRelationForAutoMappedTransferObjectType?

2023-03-10 12:14 UTC, bencegelei commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/structure/transferDeclarationTransferAttribute.etl
> +      log.debug("Created TransferAttribute (Field) for TransferFieldDeclaration: [" + t.name + "] into [" + t.eContainer.name + "]");
> TransferAttribute (Field)

TransferAttribute (Derived)?

2023-03-10 12:14 UTC, bencegelei commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/structure/transferDeclarationTransferRelation.etl
> +        // t.embeddedDelete = not s.eContainer.isAbstract;
WIP or ticket?

2023-03-10 12:14 UTC, bencegelei commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/structure/transferDeclarationTransferRelation.etl
> +      t.setId("(jsl/" + s.getId() + ")/CreateTransferObjectEmbeddedRelationForMappedTransferFieldDeclaration");
> t.setId("(jsl/" + s.getId() + ")/CreateTransferObjectEmbeddedRelationForMappedTransferFieldDeclaration");

CreateDerivedTransferObjectEmbeddedRelationForTransferFieldDeclaration?

2023-03-10 12:14 UTC, bencegelei commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/structure/transferDeclarationTransferRelation.etl
> +      t.setId("(jsl/" + s.getId() + ")/CreateTransferObjectEmbeddedRelationForMappedTransferFieldDeclaration");
CreateMappedTransferObjectEmbeddedRelationForTransferFieldDeclaration or CreateTransferObjectEmbeddedRelationForMappedTransferFieldDeclaration

2023-03-10 13:42 UTC, robertcsakany commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/structure/transferDeclarationTransferRelation.etl
> +        // t.embeddedDelete = not s.eContainer.isAbstract;
WIP

2023-03-10 14:21 UTC, bencegelei approved these changes

2023-03-10 14:44 UTC, merged