JNG-4767 JSL UI syntax
BlackBeltTechnology/judo-tatami-jsl pull request #181
Opened 2023-06-15 14:22 UTC by gprivi

JNG-4767 JSL UI syntax

2023-06-15 20:45 UTC, robertcsakany requested changes

2023-06-15 20:45 UTC, robertcsakany commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/operations/jsl/data/entityIdentifierDeclaration.eol
> +//}
Dead code. Is identifier exists?

2023-06-15 20:45 UTC, robertcsakany commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/operations/jsl/data/entityIdentifierDeclaration.eol
> +//}
And please remove EOL file if empty

2023-06-15 20:45 UTC, robertcsakany commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/operations/jsl/data/entityQueryDeclaration.eol
> +//}
Please remove deasd code

2023-06-15 20:45 UTC, robertcsakany commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/operations/jsl/data/entityIdentifierDeclaration.eol
> +//}
Please remove dead code and the file

2023-06-15 20:45 UTC, robertcsakany commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/data/primitiveTypedElement.etl
> +//
Please remove dead code

2023-06-15 20:45 UTC, robertcsakany commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/structure/entityDeclarationAutoMappedTransferAttribute.etl
> +//}
Please remove dead code

2023-06-15 20:45 UTC, robertcsakany commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/structure/entityDeclarationAutoMappedTransferObjectType.etl
> +//                    t.attributes.add(im.equivalentWithPrefix("CloneIdentifierTransferAttributeForAutoMappedTransferObjectType", t.getId()));
Please remove dead code

2023-06-15 20:45 UTC, robertcsakany commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/structure/entityDeclarationDefaultTransferAttribute.etl
> +//}
Please remove dead code

2023-06-15 20:45 UTC, robertcsakany commented on judo-tatami-jsl-jsl2psm/src/main/epsilon/transformations/psm/modules/structure/transferDeclarationTransferAttribute.etl
> +
Please remove dead code

2023-06-16 07:19 UTC, gaborflorian approved these changes

2023-06-16 11:18 UTC, bencegelei approved these changes

2023-06-18 11:11 UTC, merged