JNG-5837 transform data types
BlackBeltTechnology/judo-tatami-jsl pull request #241
Opened 2024-07-11 21:55 UTC by noherczeg

2024-07-11 22:02 UTC, robertcsakany requested changes

2024-07-11 22:02 UTC, robertcsakany commented on judo-tatami-jsl-jsl2ui/src/main/epsilon/operations/jsl/data/modifiable.eol
> +
Formatting lamda separated with space (ant there is other cases)

2024-07-11 22:18 UTC, robertcsakany approved these changes

2024-07-12 07:27 UTC, Madmat8 approved these changes

2024-07-12 08:24 UTC, merged